import { test, expect } from '../../fixtures/test-context'
import { byTestId } from '../testid'
import { loginAsAdmin, getCurrentUserToken } from '../../common/auth-helpers'
import {
  createProviderViaAPI,
  assignProviderToAdministratorsGroup,
} from '../../common/provider-helpers'
import { createBridgeToolModel, HAS_BRIDGE, BRIDGE_SKIP } from './helpers/agent-llm-helpers'
import { goToNewChatPage, selectModelInDropdown } from './helpers/chat-helpers'
import { ExternalMcpMockServer } from '../mcp/helpers/external-mcp-mock-server'

/**
 * TEST-3b [acceptance, INV-3] — THE BREAKOUT, ON A REAL STREAM.
 *
 * INV-3: "Anything that needs the user breaks out of the rail: a request for
 * input is never collapsed into a rail row."
 *
 * ── Why this spec exists alongside `activity-rail-breakout.spec.ts` ───────────
 * The sibling spec proves the same invariant against `mockChatTokenStream`, i.e.
 * `page.route()`-intercepted SSE. That gives a deterministic three-step shape
 * (two completed tools + one pending approval) which is what makes its
 * *structural* assertions non-vacuous — but it also means the invariant's
 * acceptance proof never touches the code that produces a real
 * `mcp_approval_required` frame.
 *
 * FIX_ROUND-1 established why that matters concretely: INV-5's acceptance test
 * passed the entire time the implementation rendered a failure as a `disabled`,
 * 50%-opacity, unfocusable button — the exact inverse of the invariant — because
 * the test checked the MECHANISM (is the rail open?) rather than the RENDERED
 * OUTCOME a human sees. So this spec drives the invariant through the whole
 * production path and asserts the outcome:
 *
 *   real bridge model (tool-capable)
 *     → real agent/chat loop
 *       → real EXTERNAL MCP server (a live Node HTTP process, NOT page.route)
 *         → real `manual_approve` gate → real `tool_use_approvals` row
 *           → real SSE `mcp_approval_required` frame
 *             → the rendered approve/deny surface
 *
 * There is not one `page.route()` in this file (coding-guidelines §14: no
 * `page.route()` API mocking in e2e). `ExternalMcpMockServer` is a real server
 * standing in for a third-party host — the external boundary, not our stack.
 *
 * ── How it identifies the pending step without knowing its id ─────────────────
 * On a real stream the `tool_use_id` is generated by the model, so the spec
 * cannot hardcode it the way the mocked sibling does. `ChatMessage` renders the
 * breakout with the SAME `data-step-key` a rail row would have carried, so the
 * spec reads the key off the breakout and then proves no rail step anywhere on
 * the page carries it. That is INV-3 stated as a falsifiable structural claim
 * about the real, server-chosen identity.
 *
 * Skips cleanly when the bridge env is unset (OPENAI_BASE_URL + OPENAI_API_KEY +
 * ZIEE_TEST_LLM_MODEL). Run with --workers=1.
 */
test.describe('Activity rail — a request for input breaks OUT of the rail, on a REAL stream (INV-3)', () => {
  test.skip(!HAS_BRIDGE, BRIDGE_SKIP)
  test.setTimeout(300_000)

  let mock: ExternalMcpMockServer | undefined

  test.afterEach(async () => {
    await mock?.dispose()
    mock = undefined
  })

  test('a real pending approval renders outside the rail, actionable, and nothing can collapse it', async ({
    page,
    testInfra,
  }) => {
    const { baseURL, apiURL } = testInfra
    await loginAsAdmin(page, baseURL)
    const token = await getCurrentUserToken(page)
    const auth = { Authorization: `Bearer ${token}` }

    // A tool-capable bridge model, so the model can genuinely choose to call.
    const providerId = await createProviderViaAPI(apiURL, token, 'OpenAI', 'openai')
    await assignProviderToAdministratorsGroup(apiURL, token, providerId)
    await createBridgeToolModel(page, apiURL, token, providerId, 'Rail Breakout Model')

    // A REAL external MCP server (live HTTP process on a non-loopback local IP).
    mock = await ExternalMcpMockServer.start()
    const created = await page.request.post(`${apiURL}/api/mcp/system-servers`, {
      headers: auth,
      data: {
        name: `rail_breakout_${Date.now()}`,
        display_name: 'Rail Breakout Partner Server',
        description: 'external partner lookup server for the INV-3 real-stream proof',
        enabled: true,
        transport_type: 'http',
        url: mock.url(),
        timeout_seconds: 120,
        usage_mode: 'auto',
      },
    })
    expect(
      created.ok(),
      `create server failed: ${created.status()} ${await created.text()}`,
    ).toBeTruthy()
    const serverId = (await created.json()).id as string

    // Grant it to the default group so a new conversation attaches it.
    const groupsBody = await (
      await page.request.get(`${apiURL}/api/groups`, { headers: auth })
    ).json()
    const groups = Array.isArray(groupsBody) ? groupsBody : (groupsBody.groups ?? [])
    const dg =
      groups.find((g: { is_default?: boolean }) => g.is_default) ??
      groups.find((g: { name: string }) => g.name === 'Users')
    await page.request.post(`${apiURL}/api/mcp/system-servers/${serverId}/groups`, {
      headers: auth,
      data: { group_ids: [dg.id] },
    })

    // MANUAL approval — this is what turns a tool call into a request for input.
    await page.request.put(`${apiURL}/api/mcp/defaults`, {
      headers: auth,
      data: {
        selected_servers: [{ server_id: serverId, tools: [] }],
        disabled_servers: [],
        approval_mode: 'manual_approve',
        auto_approved_tools: [],
      },
    })

    await goToNewChatPage(page, baseURL)
    await selectModelInDropdown(page, 'Rail Breakout Model')

    const textarea = page.locator('textarea[placeholder*="Type your message"]')
    await textarea.fill(
      `Call the \`${ExternalMcpMockServer.TOOL_NAME}\` tool NOW with the argument ` +
        `query set to exactly "CRISPR delivery vectors". Do not answer from your own ` +
        `knowledge — you MUST call the tool.`,
    )
    await page.getByRole('button', { name: 'Send message' }).click()

    // ── 1. The request for input is VISIBLE and ACTIONABLE with no disclosure
    //       step in the way. This is the rendered outcome a human sees.
    const breakout = page.getByTestId('rail-breakout').first()
    await expect(breakout).toBeVisible({ timeout: 240_000 })

    const approveOnce = breakout.locator('[data-testid="tool-approval-approve-once"]')
    const deny = breakout.locator('[data-testid="tool-approval-deny"]')
    await expect(approveOnce).toBeVisible()
    await expect(deny).toBeVisible()
    await expect(approveOnce).toBeEnabled()
    await expect(deny).toBeEnabled()

    // Legible, not merely present: INV-5's regression was a control rendered at
    // 50% opacity and unfocusable while its own acceptance test stayed green. So
    // assert the two properties that failure actually destroyed.
    const opacity = await approveOnce.evaluate(
      el => getComputedStyle(el as HTMLElement).opacity,
    )
    expect(
      Number(opacity),
      'the approve control must not be rendered dimmed/disabled',
    ).toBeGreaterThanOrEqual(0.99)
    await approveOnce.focus()
    await expect(approveOnce).toBeFocused()
    await deny.focus()
    await expect(deny).toBeFocused()

    // The full external-server disclosure came through the real path too — proof
    // this is the production approval surface, not a stub that merely shares a
    // testid.
    await expect(byTestId(page, 'mcp-tool-approval-card').first()).toBeVisible()
    await expect(breakout.locator('[data-testid="approval-tool-args"]')).toContainText(
      'CRISPR delivery vectors',
    )

    // ── 2. The step the SERVER chose is NOT collapsed into a rail row.
    //       The id is the model's, so read it off the breakout rather than
    //       hardcoding it.
    const stepKey = await breakout.getAttribute('data-step-key')
    expect(stepKey, 'the breakout must expose the step identity it was given').toBeTruthy()
    await expect(
      page.locator(`[data-testid="rail-step"][data-step-key="${stepKey}"]`),
      'the pending request was collapsed into a rail row — INV-3 violated',
    ).toHaveCount(0)
    await expect(
      page.locator(`[data-testid="activity-rail-steps"] [data-step-key="${stepKey}"]`),
    ).toHaveCount(0)
    // Nor nested inside a rail by any other route.
    await expect(page.locator('[data-testid="activity-rail"] [data-testid="rail-breakout"]')).toHaveCount(0)
    await expect(breakout.getByTestId('activity-rail')).toHaveCount(0)

    // ── 3. FULL WIDTH — it spans the bubble, unlike an indented rail row.
    const widths = await breakout.evaluate(el => {
      const b = el as HTMLElement
      return {
        breakout: b.getBoundingClientRect().width,
        parent: (b.parentElement as HTMLElement).getBoundingClientRect().width,
      }
    })
    expect(widths.breakout).toBeGreaterThan(0)
    expect(widths.breakout).toBeGreaterThanOrEqual(widths.parent - 1)

    // ── 4. NO control inside it can take the decision away. Actuate EVERY
    //       disclosure control in the breakout and re-assert after each.
    const disclosures = breakout.locator('[aria-expanded]')
    const disclosureCount = await disclosures.count()
    for (let i = 0; i < disclosureCount; i++) {
      await disclosures.nth(i).click({ force: true })
      await expect(
        breakout.locator('[data-testid="tool-approval-approve-once"]'),
        'a control inside the breakout hid the approval decision',
      ).toBeVisible()
    }
    await expect(breakout.getByRole('button', { name: /^(collapse|hide)\b/i })).toHaveCount(0)
    await expect(breakout.getByTestId('activity-rail-summary')).toHaveCount(0)
    await expect(breakout.getByTestId('rail-step-toggle')).toHaveCount(0)

    // ── 5. If this turn ALSO produced a rail, the breakout is its sibling and
    //       collapsing the rail does not hide the request.
    //
    //       Stated conditionally on purpose: on a real stream the model decides
    //       how many tools it calls, so a turn with exactly one (approval-gated)
    //       call legitimately renders no rail at all. Steps 1–4 above are
    //       unconditional and are what INV-3 actually governs; the mocked sibling
    //       spec owns the deterministic multi-step structural shape.
    const rail = page.getByTestId('activity-rail').first()
    if (await rail.isVisible().catch(() => false)) {
      const isSibling = await page.evaluate(() => {
        const b = document.querySelector('[data-testid="rail-breakout"]')
        const r = document.querySelector('[data-testid="activity-rail"]')
        return !!b && !!r && b.parentElement === r.parentElement
      })
      expect(isSibling, 'the breakout must be a sibling of the rail').toBe(true)

      const summary = rail.getByTestId('activity-rail-summary')
      if (await summary.isVisible().catch(() => false)) {
        if ((await summary.getAttribute('aria-expanded')) === 'true') {
          await summary.click()
          await expect(summary).toHaveAttribute('aria-expanded', 'false')
        }
        await expect(rail.getByTestId('activity-rail-steps')).toHaveCount(0)
      }
      await expect(breakout).toBeVisible()
      await expect(
        breakout.locator('[data-testid="tool-approval-approve-once"]'),
      ).toBeVisible()
    }

    // ── 6. The decision RESOLVES through the real path: deny it, and the real
    //       backend clears the request. This is the half a mocked stream cannot
    //       reach at all — the mocked sibling stops at "the controls are
    //       enabled and focusable" for exactly that reason.
    await deny.click()
    await expect(breakout.locator('[data-testid="tool-approval-approve-once"]')).toHaveCount(
      0,
      { timeout: 120_000 },
    )
  })
})
