import { test, expect } from '../../fixtures/test-context'
import { loginAsAdmin, getCurrentUserToken } from '../../common/auth-helpers'
import {
  createProviderViaAPI,
  assignProviderToAdministratorsGroup,
} from '../../common/provider-helpers'
import { createBridgeToolModel, HAS_BRIDGE, BRIDGE_SKIP } from './helpers/agent-llm-helpers'
import { goToNewChatPage, selectModelInDropdown } from './helpers/chat-helpers'
import { ExternalMcpMockServer } from '../mcp/helpers/external-mcp-mock-server'

/**
 * TEST-3b [acceptance, INV-3] — THE BREAKOUT, ON A REAL STREAM.
 *
 * INV-3: "Anything that needs the user breaks out of the rail: a request for
 * input is never collapsed into a rail row."
 *
 * ── Why this spec exists alongside `activity-rail-breakout.spec.ts` ───────────
 * The sibling spec proves the same invariant against `mockChatTokenStream`, i.e.
 * `page.route()`-intercepted SSE. That gives a deterministic three-step shape
 * (two completed tools + one pending approval) which is what makes its
 * *structural* assertions non-vacuous — but it also means the invariant's
 * acceptance proof never touches the code that produces a real
 * `mcp_approval_required` frame.
 *
 * FIX_ROUND-1 established why that matters concretely: INV-5's acceptance test
 * passed the entire time the implementation rendered a failure as a `disabled`,
 * 50%-opacity, unfocusable button — the exact inverse of the invariant — because
 * the test checked the MECHANISM (is the rail open?) rather than the RENDERED
 * OUTCOME a human sees. So this spec drives the invariant through the whole
 * production path and asserts the outcome:
 *
 *   real bridge model (tool-capable)
 *     → real agent/chat loop
 *       → real EXTERNAL MCP server (a live Node HTTP process, NOT page.route)
 *         → real `manual_approve` gate → real `tool_use_approvals` row
 *           → real SSE `mcp_approval_required` frame
 *             → the rendered approve/deny surface
 *
 * There is not one `page.route()` in this file (coding-guidelines §14: no
 * `page.route()` API mocking in e2e). `ExternalMcpMockServer` is a real server
 * standing in for a third-party host — the external boundary, not our stack.
 *
 * ── How it identifies the pending step without knowing its id ─────────────────
 * On a real stream the `tool_use_id` is generated by the model, so the spec
 * cannot hardcode it the way the mocked sibling does. `ChatMessage` renders the
 * breakout with the SAME `data-step-key` a rail row would have carried, so the
 * spec reads the key off the breakout and then proves no rail step anywhere on
 * the page carries it. That is INV-3 stated as a falsifiable structural claim
 * about the real, server-chosen identity.
 *
 * Skips cleanly when the bridge env is unset (OPENAI_BASE_URL + OPENAI_API_KEY +
 * ZIEE_TEST_LLM_MODEL). Run with --workers=1.
 */
test.describe('Activity rail — a request for input breaks OUT of the rail, on a REAL stream (INV-3)', () => {
  test.skip(!HAS_BRIDGE, BRIDGE_SKIP)
  test.setTimeout(300_000)

  let mock: ExternalMcpMockServer | undefined

  test.afterEach(async () => {
    await mock?.dispose()
    mock = undefined
  })

  test('a real pending approval renders outside the rail, actionable, and nothing can collapse it', async ({
    page,
    testInfra,
  }) => {
    const { baseURL, apiURL } = testInfra
    await loginAsAdmin(page, baseURL)
    const token = await getCurrentUserToken(page)
    const auth = { Authorization: `Bearer ${token}` }

    // A tool-capable bridge model, so the model can genuinely choose to call.
    const providerId = await createProviderViaAPI(apiURL, token, 'OpenAI', 'openai')
    await assignProviderToAdministratorsGroup(apiURL, token, providerId)
    await createBridgeToolModel(page, apiURL, token, providerId, 'Rail Breakout Model')

    // A REAL external MCP server (live HTTP process on a non-loopback local IP).
    mock = await ExternalMcpMockServer.start()
    const created = await page.request.post(`${apiURL}/api/mcp/system-servers`, {
      headers: auth,
      data: {
        name: `rail_breakout_${Date.now()}`,
        display_name: 'Rail Breakout Partner Server',
        description: 'external partner lookup server for the INV-3 real-stream proof',
        enabled: true,
        transport_type: 'http',
        url: mock.url(),
        timeout_seconds: 120,
        usage_mode: 'auto',
      },
    })
    expect(
      created.ok(),
      `create server failed: ${created.status()} ${await created.text()}`,
    ).toBeTruthy()
    const serverId = (await created.json()).id as string

    // Grant it to the default group so a new conversation attaches it.
    const groupsBody = await (
      await page.request.get(`${apiURL}/api/groups`, { headers: auth })
    ).json()
    const groups = Array.isArray(groupsBody) ? groupsBody : (groupsBody.groups ?? [])
    const dg =
      groups.find((g: { is_default?: boolean }) => g.is_default) ??
      groups.find((g: { name: string }) => g.name === 'Users')
    await page.request.post(`${apiURL}/api/mcp/system-servers/${serverId}/groups`, {
      headers: auth,
      data: { group_ids: [dg.id] },
    })

    // MANUAL approval — this is what turns a tool call into a request for input.
    await page.request.put(`${apiURL}/api/mcp/defaults`, {
      headers: auth,
      data: {
        selected_servers: [{ server_id: serverId, tools: [] }],
        disabled_servers: [],
        approval_mode: 'manual_approve',
        auto_approved_tools: [],
      },
    })

    await goToNewChatPage(page, baseURL)
    await selectModelInDropdown(page, 'Rail Breakout Model')

    const textarea = page.locator('textarea[placeholder*="Type your message"]')
    await textarea.fill(
      `Call the \`${ExternalMcpMockServer.TOOL_NAME}\` tool NOW with the argument ` +
        `query set to exactly "CRISPR delivery vectors". Do not answer from your own ` +
        `knowledge — you MUST call the tool.`,
    )
    await page.getByRole('button', { name: 'Send message' }).click()

    // ── 1. The request for input is VISIBLE and ACTIONABLE with no disclosure
    //       step in the way. This is the rendered outcome a human sees.
    const breakout = page.getByTestId('rail-breakout').first()
    await expect(breakout).toBeVisible({ timeout: 240_000 })

    const approveOnce = breakout.locator('[data-testid="tool-approval-approve-once"]')
    const deny = breakout.locator('[data-testid="tool-approval-deny"]')
    await expect(approveOnce).toBeVisible()
    await expect(deny).toBeVisible()
    await expect(approveOnce).toBeEnabled()
    await expect(deny).toBeEnabled()

    // Legible, not merely present: INV-5's regression was a control rendered at
    // 50% opacity and unfocusable while its own acceptance test stayed green. So
    // assert the two properties that failure actually destroyed.
    // FIX_ROUND-3: read the EFFECTIVE opacity, not the button's own. CSS opacity
    // composites down the ancestor chain, so a card or breakout wrapper rendered
    // at `opacity-50` still reports `1` on the button and would have passed.
    const opacity = await approveOnce.evaluate(el => {
      let node: HTMLElement | null = el as HTMLElement
      let effective = 1
      while (node) {
        effective *= Number(getComputedStyle(node).opacity || '1')
        node = node.parentElement
      }
      return effective
    })
    expect(
      Number(opacity),
      'the approve control must not be rendered dimmed/disabled (at any level)',
    ).toBeGreaterThanOrEqual(0.99)
    await approveOnce.focus()
    await expect(approveOnce).toBeFocused()
    await deny.focus()
    await expect(deny).toBeFocused()

    // The full external-server disclosure came through the real path too — proof
    // this is the production approval surface, not a stub that merely shares a
    // testid.
    // FIX_ROUND-3: scoped to the BREAKOUT, not the page. Page-scoped, a card
    // rendered anywhere satisfied it, which is not the claim being made.
    await expect(breakout.getByTestId('mcp-tool-approval-card').first()).toBeVisible()
    await expect(breakout.locator('[data-testid="approval-tool-args"]')).toContainText(
      'CRISPR delivery vectors',
    )

    // ── 2. The step the SERVER chose is NOT collapsed into a rail row.
    //       The id is the model's, so read it off the breakout rather than
    //       hardcoding it.
    const stepKey = await breakout.getAttribute('data-step-key')
    expect(stepKey, 'the breakout must expose the step identity it was given').toBeTruthy()
    await expect(
      page.locator(`[data-testid="rail-step"][data-step-key="${stepKey}"]`),
      'the pending request was collapsed into a rail row — INV-3 violated',
    ).toHaveCount(0)
    await expect(
      page.locator(`[data-testid="activity-rail-steps"] [data-step-key="${stepKey}"]`),
    ).toHaveCount(0)
    // Nor nested inside a rail by any other route.
    await expect(page.locator('[data-testid="activity-rail"] [data-testid="rail-breakout"]')).toHaveCount(0)
    await expect(breakout.getByTestId('activity-rail')).toHaveCount(0)

    // ── 3. FULL WIDTH, measured against a RAIL ROW — it spans the bubble where
    //       an indented rail step does not.
    //
    //       FIX_ROUND-3: comparing the breakout to its own parent only restated
    //       `w-full`, a class this same change added — the assertion could not
    //       fail for any reason INV-3 is about.
    //
    //       FIX_ROUND-4: the rail-row comparison FR3 added to fix that was
    //       itself wrong twice over — it used a document-wide
    //       `querySelector('[data-testid="rail-step"]')`, so it could pick a row
    //       from another message, and the QUIET-SINGLE rail shape renders its
    //       row at full bubble width (DEC-3), making `breakout > railRow` go RED
    //       on a design-conformant render. Scope it to an INDENTED rail
    //       (`data-rail-shape="rail"`) inside the SAME message bubble — the only
    //       shape for which "the breakout is not laid out as a rail row" is a
    //       claim at all.
    const widths = await breakout.evaluate(el => {
      const b = el as HTMLElement
      const bubble = b.parentElement as HTMLElement
      const row = bubble.querySelector(
        '[data-rail-shape="rail"] [data-testid="rail-step"]',
      ) as HTMLElement | null
      return {
        breakout: b.getBoundingClientRect().width,
        parent: bubble.getBoundingClientRect().width,
        railRow: row ? row.getBoundingClientRect().width : null,
      }
    })
    expect(widths.breakout).toBeGreaterThan(0)
    expect(widths.breakout).toBeGreaterThanOrEqual(widths.parent - 1)
    if (widths.railRow !== null) {
      expect(
        widths.breakout,
        'the breakout must be WIDER than an indented rail row, not laid out as one',
      ).toBeGreaterThan(widths.railRow)
    }

    // ── 4. NO control inside it can take the decision away. Actuate EVERY
    //       disclosure control in the breakout and re-assert after each.
    //
    //       FIX_ROUND-3: re-read the set on every iteration (expanding one
    //       disclosure can reveal another, and the pre-fix loop cached the count
    //       before the first click so those were never actuated), and drop
    //       `force: true` — bypassing actionability meant a control that was
    //       genuinely obscured or zero-size still counted as "actuated".
    for (let i = 0; ; i++) {
      const disclosures = breakout.locator('[aria-expanded]')
      if (i >= (await disclosures.count())) break
      await disclosures.nth(i).click()
      await expect(
        breakout.locator('[data-testid="tool-approval-approve-once"]'),
        'a control inside the breakout hid the approval decision',
      ).toBeVisible()
      // Guard against an unbounded loop if a click ever spawns disclosures.
      expect(i, 'implausibly many disclosure controls inside one breakout').toBeLessThan(50)
    }
    // The breakout must carry NO rail chrome. `activity-rail-summary` /
    // `rail-step-toggle` are the only two collapse affordances the rail ships,
    // so their absence is what "nothing can collapse it" means structurally.
    // (The `collapse|hide`-named-button probe the first cut also had matched
    // nothing that exists in the kit and was removed rather than left to read as
    // coverage.)
    await expect(breakout.getByTestId('activity-rail-summary')).toHaveCount(0)
    await expect(breakout.getByTestId('rail-step-toggle')).toHaveCount(0)

    // ── 5. If this turn ALSO produced a rail, the breakout is its sibling and
    //       collapsing the rail does not hide the request.
    //
    //       Stated conditionally on purpose: on a real stream the model decides
    //       how many tools it calls, so a turn with exactly one (approval-gated)
    //       call legitimately renders no rail at all. Steps 1–4 above are
    //       unconditional and are what INV-3 actually governs; the mocked sibling
    //       spec owns the deterministic multi-step structural shape.
    //       FIX_ROUND-3, two defects in this block:
    //        (a) `.first()` could select the QUIET-SINGLE rail shape, which also
    //            carries `data-testid="activity-rail"` but renders no summary —
    //            silently no-opping the whole block even when a real multi-step
    //            rail existed further down. Select a rail that HAS a summary.
    //        (b) the steps-collapsed assertion sat OUTSIDE the `aria-expanded`
    //            branch. A rail that INV-4/INV-5 force open renders its summary
    //            as a plain div with no `aria-expanded` and no collapse control,
    //            so no click happened, the steps stayed rendered, and this INV-3
    //            spec went RED on a design-conformant rendering of INV-4/INV-5.
    //            The collapse assertion now lives inside the toggleable branch,
    //            where it is the actual claim; the forced-open case asserts the
    //            thing INV-3 governs there — the breakout survives regardless.
    //       FIX_ROUND-6: the GATE is scoped to the breakout's own message too.
    //       Scoping only the probe left a document-wide `.first()` summary-bearing
    //       rail deciding whether the block runs — so in a multi-turn transcript
    //       where an earlier turn rendered a rail and the breakout's turn did not,
    //       the gate opened and the breakout-anchored probe returned false: a
    //       false RED for a reason INV-3 does not govern.
    const bubble = breakout.locator('xpath=..')
    const rail = bubble
      .getByTestId('activity-rail')
      .filter({ has: page.getByTestId('activity-rail-summary') })
      .first()
    if (await rail.isVisible().catch(() => false)) {
      // FIX_ROUND-5: BOTH sides scoped, from the breakout outward. FIX_ROUND-4
      // narrowed the `rail` locator but left the breakout resolved document-wide
      // inside the evaluate, so in a multi-turn transcript the probe could pair a
      // breakout in message N against a rail in message N-1 — and because the
      // rail was now filtered to summary-bearing rails while the breakout was
      // not, the pairing could be MORE mismatched than before the narrowing.
      const isSibling = await breakout.evaluate(b => {
        const parent = b.parentElement
        if (!parent) return false
        return Array.from(parent.children).some(
          el => el !== b && el.getAttribute('data-testid') === 'activity-rail',
        )
      })
      expect(isSibling, 'the breakout must be a sibling of the rail').toBe(true)

      // NOTE, stated rather than implied: the collapse leg the first cut had here
      // could not execute in this spec's configuration. `ActivityRail` sets
      // `toggleable = !hasFailure && !isStreaming`, and at the pending-approval
      // moment the stream is still open — so INV-4/INV-5 render the summary as a
      // plain div with no `aria-expanded` and no collapse control, and the
      // click-then-assert branch was dead while still reading as coverage. The
      // deterministic "collapsing the rail does not hide the request" proof is
      // owned by the mocked sibling (`activity-rail-breakout.spec.ts`), which can
      // guarantee a settled, toggleable rail; a real stream cannot. Removed here
      // rather than left as decoration.
      await expect(breakout).toBeVisible()
      await expect(
        breakout.locator('[data-testid="tool-approval-approve-once"]'),
      ).toBeVisible()
    }

    // ── 6. The decision RESOLVES through the real path: deny it, and the real
    //       backend clears the request. This is the half a mocked stream cannot
    //       reach at all — the mocked sibling stops at "the controls are
    //       enabled and focusable" for exactly that reason.
    await deny.click()
    await expect(breakout.locator('[data-testid="tool-approval-approve-once"]')).toHaveCount(
      0,
      { timeout: 120_000 },
    )
  })
})
