// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  cancelInstall: typeof import('./actions/cancelInstall')['default']
  dismissError: typeof import('./actions/dismissError')['default']
  ensureLocalProvider: typeof import('./actions/ensureLocalProvider')['default']
  ensureRuntime: typeof import('./actions/ensureRuntime')['default']
  install: typeof import('./actions/install')['default']
  loadContext: typeof import('./actions/loadContext')['default']
}
