// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  deleteWorkflow: typeof import('./actions/deleteWorkflow')['default']
  dryRun: typeof import('./actions/dryRun')['default']
  getWorkflow: typeof import('./actions/getWorkflow')['default']
  importWorkflow: typeof import('./actions/importWorkflow')['default']
  installFromHub: typeof import('./actions/installFromHub')['default']
  loadWorkflows: typeof import('./actions/loadWorkflows')['default']
  run: typeof import('./actions/run')['default']
  test: typeof import('./actions/test')['default']
  updateWorkflow: typeof import('./actions/updateWorkflow')['default']
  validateWorkflow: typeof import('./actions/validateWorkflow')['default']
}
