// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  attachFile: typeof import('./actions/attachFile')['default']
  batchDetach: typeof import('./actions/batchDetach')['default']
  clearError: typeof import('./actions/clearError')['default']
  deselectAll: typeof import('./actions/deselectAll')['default']
  detachFile: typeof import('./actions/detachFile')['default']
  dismissUploadingFile: typeof import('./actions/dismissUploadingFile')['default']
  loadFiles: typeof import('./actions/loadFiles')['default']
  selectAll: typeof import('./actions/selectAll')['default']
  toggleSelection: typeof import('./actions/toggleSelection')['default']
  uploadAndAttachFiles: typeof import('./actions/uploadAndAttachFiles')['default']
}
