import { Shrink, ChevronRight, ChevronDown } from 'lucide-react'
import { useState } from 'react'
import { Card, Separator, Flex, Text } from '@ziee/kit'
import { useMessageContext } from '@/modules/chat/core/MessageContext'
import { ConversationSummarization } from '@/modules/summarization/stores/conversationSummarization'
import { Chat } from '@/modules/chat/core/stores/chatBridge'

/**
 * In-thread persistent marker shown on the boundary message — i.e. the
 * message whose `id` equals the summary's `summarized_up_to_id`.
 *
 * Registered in the `message_footer` slot (rendered inside
 * `MessageContext.Provider` per `ChatMessage.tsx`). Each
 * `ChatMessage` mounts one instance; the instance whose message id
 * matches the summary anchor renders the divider, the others return
 * null. Cheap — every other instance bails out in the first useState
 * call.
 *
 * `message_footer` was chosen over `message_item_prefix` /
 * `message_item_suffix` (the prior session's audit confirmed the
 * suffix slot isn't actually rendered, and prefix sits before the
 * message bubble — visually misleading for a "earlier turns
 * condensed" marker). The footer sits directly below the last
 * condensed turn, which reads naturally.
 *
 * The summary itself lives in `ConversationSummarization.current`
 * — loaded by `SummarizationStatusPill` when a conversation is opened
 * or switched to, and by the summarization extension's
 * `afterStreamComplete` hook at the end of each turn. It is NOT
 * reloaded per message any more; see `summaryRefreshTrigger.ts`.
 *
 * `ConversationSummarization` is a SINGLE-ENTRY store, so `current`
 * can belong to a different conversation than the message this
 * instance renders for (two split panes; a pane sitting on the
 * new-chat route). The conversation guard below is what stops this
 * marker from attaching another conversation's summary to a message
 * that merely shares an id space.
 */
export function SummaryBoundaryMarker() {
  const message = useMessageContext()
  const current = ConversationSummarization.current
  const conversationId = Chat.conversation?.id ?? null
  const [expanded, setExpanded] = useState(false)

  if (!message) return null
  if (!current?.summary) return null
  // Single-entry store: only render when the held summary belongs to the
  // conversation this marker is rendering inside.
  if (!conversationId || current.conversationId !== conversationId) return null
  if (current.summary.summarized_up_to_id !== message.id) return null

  const summary = current.summary
  const updatedAt = new Date(summary.updated_at).toLocaleString()

  return (
    <div className="mt-3 mb-1">
      <Separator>
        <Flex
          data-testid="summ-boundary-toggle"
          align="center"
          gap="middle"
          className="cursor-pointer select-none"
          role="button"
          tabIndex={0}
          aria-expanded={expanded}
          aria-label={
            expanded
              ? 'Collapse condensed-conversation summary'
              : 'Expand condensed-conversation summary'
          }
          onClick={() => setExpanded(!expanded)}
          onKeyDown={e => {
            if (e.key === 'Enter' || e.key === ' ') {
              e.preventDefault()
              setExpanded(!expanded)
            }
          }}
        >
          <Shrink className="opacity-70" />
          <Text type="secondary" className="text-xs">
            Earlier {summary.message_count} messages condensed into a summary
          </Text>
          {expanded ? (
            <ChevronDown className="text-[10px] opacity-50" />
          ) : (
            <ChevronRight className="text-[10px] opacity-50" />
          )}
        </Flex>
      </Separator>
      {expanded && (
        <Card size="sm" data-testid="summ-boundary-card" className="mb-3">
          <Text
            type="secondary"
            className="whitespace-pre-wrap text-xs mb-2"
          >
            {summary.summary_text}
          </Text>
          <Text type="secondary" className="text-[11px]">
            {summary.model_used
              ? `Generated by ${summary.model_used} at ${updatedAt}`
              : `Generated at ${updatedAt}`}
          </Text>
        </Card>
      )}
    </div>
  )
}
