import type { ValidationError } from '@/api-client/types'
import type { BuilderStep } from './stepForms'

// ---------------------------------------------------------------------------
// The PRESENTATION boundary for workflow validation findings (ITEM-1, INV-1).
//
// The backend validator is a machine-readable contract: `validate_for_install`
// turns a finding into an `AppError` for the install/import/run paths, and
// `workflow_mcp`'s `validate_workflow` tool serializes it for the MODEL. Its
// messages are therefore written in the wire vocabulary ("step has neither
// prompt: nor prompt_file:") and MUST stay that way.
//
// A person building a workflow is not reading YAML. So the humanisation lives
// HERE, keyed off the stable `ValidationError.code`, where the step's KIND is
// also known — which matters, because one backend code can mean different
// things to a person: WORKFLOW_PROMPT_MISSING on an `agent` step is a missing
// TASK, on an `llm` step a missing PROMPT.
//
// DRIFT GUARD: `validate.rs`'s `validation_codes_are_registered_and_humanised`
// test reads THIS FILE and fails the backend suite if any code it can emit has
// no entry in `HUMAN_COPY`. So a new backend finding cannot ship without human
// copy. Keep the `HUMAN_COPY` keys as plain quoted string literals — the Rust
// test matches them textually.
// ---------------------------------------------------------------------------

/** What a finding is attached to. `null` step ⇒ it concerns the whole workflow. */
export interface AttributedFinding {
  finding: ValidationError
  /** The step this finding belongs to, resolved from `location`. */
  stepId: string | null
  /** 1-based position of that step in the list (for "Step 3 · …"). */
  stepIndex: number | null
  /** The step's author-facing label (its description, else its id). */
  stepLabel: string | null
  /** Person-facing sentence. Never a raw schema key. */
  text: string
  severity: 'error' | 'warning'
}

/** Context a copy function may use to say something specific. */
interface CopyContext {
  /** The step the finding points at, when it resolves to one. */
  step?: BuilderStep
  /** The raw backend message — the fallback, and occasionally a detail source. */
  message: string
}

type CopyFn = (ctx: CopyContext) => string

/**
 * `code` → person-facing sentence.
 *
 * Rules for entries here:
 *  - say what the PERSON must do, not what the schema requires;
 *  - never name a YAML key, a Rust field, or a wire type;
 *  - stay one sentence where possible — the panel is dense.
 */
const HUMAN_COPY: Record<string, CopyFn> = {
  // ── whole-workflow shape ────────────────────────────────────────────────
  "WORKFLOW_NO_STEPS": () => 'This workflow has no steps yet — add at least one.',
  // LIMIT MIRROR: `validate.rs::check_steps_shape` — the literal `50` step cap.
  "WORKFLOW_TOO_MANY_STEPS": () =>
    'This workflow has too many steps — split it into smaller workflows (50 is the limit).',
  "WORKFLOW_SANDBOX_FLAVOR_REQUIRED": () =>
    'A step runs code, so the workflow needs a sandbox environment chosen for it.',
  "WORKFLOW_UNKNOWN_FLAVOR": () =>
    'That sandbox environment is not available on this server — pick one of the installed environments.',
  "WORKFLOW_CYCLE": () =>
    'These steps depend on each other in a loop, so there is no order that can run them — remove one of the dependencies.',
  "WORKFLOW_DUPLICATE_OUTPUT_NAME": () =>
    'Two results share the same name — give each result its own name.',

  // ── step identity ───────────────────────────────────────────────────────
  // Step ids are GENERATED by the builder (`stepForms.ts::createStep`) and the
  // builder exposes no control for them — so these two can only reach a person
  // through a workflow file they imported. The copy therefore points at the file,
  // not at a field that does not exist on this page.
  "WORKFLOW_BAD_STEP_ID": () =>
    "This step's internal name can't be used — it has to start with a lowercase letter and use only lowercase letters, numbers and underscores. Change it in the workflow file and import it again.",
  "WORKFLOW_DUPLICATE_STEP_ID": () =>
    'Two steps share the same internal name — rename one of them in the workflow file and import it again.',
  // LIMIT MIRROR: `validate.rs::MAX_STEP_DESCRIPTION_CHARS` (200). The backend
  // rejects only `> MAX`, so exactly 200 characters is VALID — say "or fewer".
  "WORKFLOW_STEP_DESCRIPTION_TOO_LONG": () =>
    'This step label is too long — shorten it to 200 characters or fewer.',

  // ── prompts ─────────────────────────────────────────────────────────────
  "WORKFLOW_PROMPT_MISSING": ({ step }) =>
    step?.kind === 'agent'
      ? 'This step needs a task description — say what the assistant should do.'
      : step?.kind === 'llm_map'
        ? 'This step needs a prompt to run for each item in the list.'
        : 'This step needs a prompt.',
  "WORKFLOW_PROMPT_BOTH": ({ step }) =>
    step?.kind === 'agent'
      ? 'This step has both a typed-in task and a task file — keep one of them.'
      : 'This step has both a typed-in prompt and a prompt file — keep one of them.',
  "WORKFLOW_PROMPT_FILE_MISSING": () =>
    "This step points at a prompt file that isn't in the workflow — add the file, or type the prompt in directly.",
  // The two file codes describe DIFFERENT author mistakes and must read
  // differently: UNSAFE (`validate.rs::check_prompt_files`, the literal `..` /
  // leading-`/` reject) is a path that was WRITTEN to leave the workflow;
  // ESCAPE is a path that looked fine but RESOLVED outside it (a symlink, or a
  // chain of segments that climbs out).
  "WORKFLOW_PROMPT_FILE_UNSAFE": () =>
    'The file this step reads its wording from is written as a location elsewhere on the machine — name a file that is stored with this workflow instead.',
  "WORKFLOW_PROMPT_FILE_ESCAPE": () =>
    'The file this step reads its wording from ends up outside the workflow once the location is followed — point it at a file that is really stored inside this workflow.',

  // ── per-kind configuration ──────────────────────────────────────────────
  "WORKFLOW_DEAD_TOOLS_FIELD": () =>
    'A prompt step cannot use tools — add a separate "Call a tool" step instead.',
  "WORKFLOW_SANDBOX_NO_RUN": () => 'This step needs a command to run.',
  "WORKFLOW_TOOL_NO_SERVER": () => 'Choose the server this step should call.',
  "WORKFLOW_TOOL_NO_TOOL": () => 'Choose the tool this step should call.',
  "WORKFLOW_ELICIT_NO_MESSAGE": () =>
    'This step needs the question to show the person running the workflow.',
  // LIMIT MIRROR: `validate.rs::ELICIT_TIMEOUT_HARD_CAP_MS` (1_800_000 ms = 30 min).
  "WORKFLOW_ELICIT_TIMEOUT_CAP": () =>
    'This step waits too long for an answer — the longest allowed wait is 30 minutes (use 0 to wait indefinitely).',
  // LIMIT MIRROR: `validate.rs::MAX_PARALLEL_HARD_CAP` (20).
  "WORKFLOW_PARALLEL_CAP": () =>
    'This step runs too many items at once — the maximum is 20.',
  "WORKFLOW_PARALLEL_ZERO": () =>
    'This step must run at least one item at a time.',
  "WORKFLOW_FOR_EACH_EMPTY": () =>
    'Choose the list this step should repeat over.',
  "WORKFLOW_FOR_EACH_NOT_TEMPLATE": () =>
    'The list to repeat over must come from an input or an earlier step — insert a reference instead of typing a value.',
  "WORKFLOW_ITEM_VAR_EMPTY": () =>
    'Give each item a name so the prompt can refer to it.',

  // ── dependencies ────────────────────────────────────────────────────────
  "WORKFLOW_UNKNOWN_DEPENDENCY": () =>
    'This step waits for a step that no longer exists — pick an existing step, or remove the dependency.',
  "WORKFLOW_SELF_DEPENDENCY": () =>
    'This step waits for itself, so it can never start — remove the dependency.',

  // ── references between steps ────────────────────────────────────────────
  // The backend message here is `TemplateError`'s Display impl (a parser
  // diagnostic — "invalid template syntax: …", "unknown filter '…'"). Pasting it
  // into author-facing copy is exactly the leak this file exists to stop, so the
  // copy names the ACT instead of quoting the parser.
  "WORKFLOW_TEMPLATE_SYNTAX": () =>
    "A reference in this step isn't written correctly — check that every {{ … }} reference is closed and names an input or an earlier step.",
  "WORKFLOW_UNKNOWN_INPUT_REF": () =>
    'This step refers to an input the workflow does not have — add that input, or point at an existing one.',
  "WORKFLOW_UNKNOWN_STEP_REF": () =>
    'This step refers to a step that does not exist — point at an existing step.',
  "WORKFLOW_BAD_STEP_FIELD": () =>
    "This step refers to something a step doesn't produce — use the step's result or its file.",
  "WORKFLOW_PATH_ACCESS": () =>
    "This step treats a file location as if it held structured data — use the step's result instead.",
  "WORKFLOW_REF_UNKNOWN_FIELD": () =>
    'This step reads a field that the earlier step does not produce — check the field name.',
  "WORKFLOW_REF_FIELD_NON_OBJECT": () =>
    'This step reads a field from something that is not structured data.',
  "WORKFLOW_REF_INDEX_NON_ARRAY": () =>
    'This step picks an item by position from something that is not a list.',
  "WORKFLOW_FOR_EACH_NOT_ARRAY": () =>
    'The list to repeat over is not a list — point at something that produces a list.',

  // ── warnings (non-blocking) ─────────────────────────────────────────────
  "WORKFLOW_FOR_EACH_TYPE_UNRESOLVED": () =>
    "We can't tell in advance whether this will be a list — double-check it produces one when the workflow runs.",
  "WORKFLOW_REF_INDEX_UNRESOLVED": () =>
    "We can't tell in advance whether this is a list — double-check it produces one when the workflow runs.",
  "WORKFLOW_REF_FIELD_UNRESOLVED": () =>
    "We can't tell in advance what fields this produces — double-check the field exists when the workflow runs.",

  // ── security / publishing ───────────────────────────────────────────────
  "WORKFLOW_ARTIFACT_PATH_UNSAFE": () =>
    "This step saves a file outside the workflow's own folder — use a path inside it.",
  "WORKFLOW_MOCK_IN_PUBLISHED": () =>
    'This step still has test stand-in data, which is only allowed while developing.',
}

/**
 * Every code this module can say in human language.
 *
 * Two consumers: `describeRequestError` below (it only rewrites a save/install
 * failure whose code it actually has copy for) and the drift test in this
 * directory (which asserts none of the copy leaks wire vocabulary).
 */
export const HUMANISED_CODES: readonly string[] = Object.keys(HUMAN_COPY)

/**
 * The person-facing sentence for a finding. An UNKNOWN code falls back to the
 * backend's own message rather than to nothing — a finding must always be
 * readable, even in the (test-prevented) case where a new code slipped through.
 */
export function humaniseFinding(
  finding: ValidationError,
  step?: BuilderStep,
): string {
  const copy = HUMAN_COPY[finding.code]
  if (!copy) return finding.message
  return copy({ step, message: finding.message })
}

/**
 * Codes whose `location` is the step id ITSELF rather than a path into the step.
 * These are the identity findings, and the id they carry is exactly the value
 * being complained about — so it must never be treated as a `step.field` path.
 */
const ID_ONLY_LOCATION_CODES: ReadonlySet<string> = new Set([
  "WORKFLOW_BAD_STEP_ID",
  "WORKFLOW_DUPLICATE_STEP_ID",
])

/**
 * The step a finding belongs to. `location` is either a bare step id (`agent_1`),
 * a step FIELD path (`agent_1.prompt`, `map.for_each`), an output path
 * (`outputs[name].from`), or absent. Anything that does not resolve to a real
 * step in `steps` is workflow-level.
 */
export function resolveFindingStep(
  finding: ValidationError,
  steps: BuilderStep[],
): BuilderStep | null {
  const loc = finding.location
  if (!loc) return null
  // `outputs[…]` is never a step.
  if (loc.startsWith('outputs[')) return null
  // 1. EXACT id first. `WORKFLOW_BAD_STEP_ID`'s location IS the malformed id
  //    (`validate.rs::check_steps_shape` passes `&s.id`), and a malformed id may
  //    itself contain a '.' — an imported `report.final`. Splitting on '.' would
  //    attribute the one finding whose entire job is to point at that id to a
  //    different step, or to "Whole workflow".
  const exact = steps.find(s => s.id === loc)
  if (exact) return exact
  // For the identity findings the location is definitionally the step id ITSELF,
  // never a field path — so a prefix match there would be a mis-attribution
  // (`report.gone` is not a field of a step called `report`).
  if (ID_ONLY_LOCATION_CODES.has(finding.code)) return null
  // 2. Otherwise it is a FIELD PATH under a step (`agent_1.prompt`,
  //    `map.for_each`). Take the LONGEST step id it is a path of, so a step
  //    named `report` never steals `report.final.prompt` from `report.final`.
  let best: BuilderStep | null = null
  for (const s of steps) {
    if (loc.startsWith(`${s.id}.`) || loc.startsWith(`${s.id}[`)) {
      if (!best || s.id.length > best.id.length) best = s
    }
  }
  return best
}

/**
 * `error` for anything the backend did not explicitly mark a warning.
 *
 * The backend ALWAYS serializes `severity` (`ValidationError.severity` carries
 * `#[serde(default = "default_severity")]` but no `skip_serializing_if`), so the
 * absent case cannot occur on the wire — the generated TS type only marks it
 * optional because `serde(default)` makes schemars drop it from `required`. The
 * fallback stays because it is the SAFE direction: an unreadable severity must
 * block Save, never silently downgrade a blocking finding to a warning.
 */
function severityOf(finding: ValidationError): 'error' | 'warning' {
  return finding.severity === 'warning' ? 'warning' : 'error'
}

/**
 * Attribute + humanise a batch of findings against the current definition.
 * Pure; the panel and the step list both consume this ONE result so they can
 * never disagree about which steps are broken.
 */
export function attributeFindings(
  findings: readonly ValidationError[],
  steps: BuilderStep[],
): AttributedFinding[] {
  return findings.map(finding => {
    const step = resolveFindingStep(finding, steps)
    const stepIndex = step ? steps.findIndex(s => s.id === step.id) : -1
    return {
      finding,
      stepId: step?.id ?? null,
      stepIndex: stepIndex >= 0 ? stepIndex + 1 : null,
      stepLabel: step ? step.description?.trim() || step.id : null,
      text: humaniseFinding(finding, step ?? undefined),
      severity: severityOf(finding),
    }
  })
}

/** Per-step finding counts, for the step list's invalid markers. */
export interface StepFindingCounts {
  errors: number
  warnings: number
}

/**
 * Index attributed findings by step id. Findings with no resolvable step land
 * under the `WORKFLOW_LEVEL` key so the panel can group them without a second
 * pass and without any step being double-counted.
 *
 * `WORKFLOW_LEVEL` is exported because it is part of the returned map's
 * contract: a caller iterating `indexFindingsByStep` needs it to tell the
 * whole-workflow bucket from a step id (`StepList` looks up step ids only, so it
 * does not read the constant — but it would silently mis-mark a step literally
 * named `__workflow__` without it).
 */
export const WORKFLOW_LEVEL = '__workflow__'

export function indexFindingsByStep(
  attributed: readonly AttributedFinding[],
): Map<string, StepFindingCounts> {
  const out = new Map<string, StepFindingCounts>()
  for (const a of attributed) {
    const key = a.stepId ?? WORKFLOW_LEVEL
    const cur = out.get(key) ?? { errors: 0, warnings: 0 }
    if (a.severity === 'error') cur.errors += 1
    else cur.warnings += 1
    out.set(key, cur)
  }
  return out
}

/** "Step 3 · Research the topic", or "Whole workflow" when unattributed. */
export function findingStepTitle(a: AttributedFinding): string {
  if (a.stepIndex == null || a.stepLabel == null) return 'Whole workflow'
  return `Step ${a.stepIndex} · ${a.stepLabel}`
}

// ---------------------------------------------------------------------------
// The SAVE/INSTALL boundary (the second place a finding reaches the author).
//
// `/validate-def` returns structured `ValidationError`s, which the panel above
// humanises. But the SAVE path does not: `validate_for_install` collapses the
// FIRST blocking finding into an `AppError` whose message is the wire string
//     [semantic/WORKFLOW_PROMPT_MISSING] agent_1: step has neither prompt: nor prompt_file:
// That string is reachable whenever the panel's `validation` is absent or stale
// — a never-validated workflow, a transient `/validate-def` failure (the store
// deliberately KEEPS the prior result), the debounce race, or the
// `prompt_file:` divergence between `/validate-def` (temp dir) and install (the
// real bundle root).
//
// So the same humanisation is applied here, by re-deriving a `ValidationError`
// from that formatted string. INV-1 is a property of the SURFACE, not of one
// code path.
//
// ONE BOUNDARY: the STORE calls `describeRequestError` when it catches the
// failure, and stores the sentence. Every renderer (the panel's Alert, the
// page's toast) shows `store.error` as-is. Humanising a second time is not
// harmless — see the warning on `describeRequestError`.
// ---------------------------------------------------------------------------

/** The pieces `validate_for_install` packs into its `AppError` message. */
export interface ParsedInstallError {
  layer: string
  code: string
  /** The step id / path the finding pointed at, when it carried one. */
  location: string | null
  message: string
}

/**
 * Parse `[layer/CODE] location: message` (or `[layer/CODE] message`).
 * Returns `null` for anything else — a network failure, a name collision, or
 * any other save error that never went through the validator.
 */
export function parseInstallError(raw: string): ParsedInstallError | null {
  const head = /^\[([a-z]+)\/([A-Z][A-Z0-9_]*)\]\s+([\s\S]+)$/.exec(raw.trim())
  if (!head) return null
  const [, layer, code, rest] = head
  // A location is a single unspaced token (`agent_1`, `agent_1.prompt`,
  // `outputs[summary].from`) followed by `: `. A finding with no location whose
  // message happens to start `word: ` mis-parses into a location that resolves
  // to no step — i.e. it degrades to workflow-level, which is what it already is.
  const withLoc = /^(\S+):\s+([\s\S]+)$/.exec(rest)
  if (withLoc) {
    return { layer, code, location: withLoc[1], message: withLoc[2] }
  }
  return { layer, code, location: null, message: rest }
}

/** Which finding a humanised failure came from, when it came from one. */
export interface FindingIdentity {
  code: string
  location: string | null
}

/**
 * The humanised sentence for a raw string that IS a validator finding, else
 * `null` (a network failure, a name collision, a code with no copy yet).
 *
 * It also returns WHICH finding it restated, because the failure outlives the
 * condition: a save rejected by `validate_for_install` keeps its message on
 * screen after the author fixes the step, so the store needs to recognise that
 * finding in a later check result to retire it.
 */
function humaniseValidatorFinding(
  raw: string,
  steps: BuilderStep[],
): { text: string; identity: FindingIdentity } | null {
  const parsed = parseInstallError(raw)
  if (!parsed) return null
  if (!HUMANISED_CODES.includes(parsed.code)) return null
  const finding = {
    layer: parsed.layer,
    code: parsed.code,
    message: parsed.message,
    ...(parsed.location != null ? { location: parsed.location } : {}),
  } as ValidationError
  const [attributed] = attributeFindings([finding], steps)
  return {
    text: attributed.stepId
      ? `${findingStepTitle(attributed)}: ${attributed.text}`
      : attributed.text,
    identity: { code: parsed.code, location: parsed.location },
  }
}

// ── the OTHER half of the save/validate boundary: transport failures ────────
//
// Not every save failure is a validator finding. When the request never reaches
// the handler (a proxy, a gateway, a dead tunnel) the generated api-client
// builds its message as
//     `HTTP error! status: 502 - <the entire response body>`
// (`sdk/packages/framework/src/api-client/core.ts`) — an unbounded machine
// string, routinely a whole HTML error page. Rendering that in an Alert TITLE
// and a toast is the same class of leak as the wire vocabulary above: a machine
// artefact where a sentence belongs. So the same treatment the tool catalog
// applies to a failed `tools/list` (`ToolCatalog.store.ts::describeFetchError` —
// status → sentence, markup stripped, length clipped) is applied HERE, at the
// save/validate boundary.

/** Longest machine-derived text we will put in front of the author. */
const MAX_ERROR_CHARS = 160

/** The api-client's transport-failure message shape. */
const HTTP_ERROR_RE = /^HTTP error!\s*status:\s*(\d{3})\b/i

/** Neutral last resort. Used for BOTH surfaces, so it names neither. */
const GENERIC_REQUEST_FAILURE = 'The server could not be reached — try again.'

/** An HTTP status the author can act on, as a sentence. `null` ⇒ say nothing. */
function statusSentence(status: number): string | null {
  if (status === 401)
    return 'You are no longer signed in — sign in again, then retry.'
  if (status === 403)
    return 'You do not have permission to make this change.'
  if (status === 404) return 'This workflow no longer exists on the server.'
  if (status === 408 || status === 504)
    return 'The server took too long to answer — try again.'
  if (status === 409)
    return 'This workflow changed on the server — reload it, then retry.'
  if (status === 413)
    return 'This workflow is too large for the server to accept.'
  if (status === 429)
    return 'The server is busy right now — wait a moment, then retry.'
  if (status >= 500)
    return 'The server reported an internal error — try again in a moment.'
  if (status >= 400) return 'The server rejected this change.'
  return null
}

/** The api-client attaches the status to the thrown Error; use it when we have
 *  the object, and fall back to the one it formatted into the message. */
function statusOf(error: unknown): number | null {
  const s = (error as { status?: unknown } | null)?.status
  if (typeof s === 'number' && Number.isFinite(s)) return s
  return null
}

/** Strip markup, collapse whitespace, clip. `''` when nothing readable is left. */
function tidyMachineText(raw: string): string {
  const oneLine = raw
    .replace(/<[^>]*>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
  if (!oneLine) return ''
  return oneLine.length > MAX_ERROR_CHARS
    ? `${oneLine.slice(0, MAX_ERROR_CHARS - 1)}…`
    : oneLine
}

/** A failure, as the author should read it — plus its provenance. */
export interface DescribedRequestError {
  /** The person-facing sentence. */
  text: string
  /** The validator finding it restates, or `null` when it is not one. */
  finding: FindingIdentity | null
}

/**
 * The person-facing sentence for ANY save/validate failure.
 *
 * Order matters:
 *  1. a validator finding wins — it is the actionable one, and a 400 that
 *     carries one must not be flattened into "the server rejected this";
 *  2. otherwise a status becomes a sentence;
 *  3. otherwise the message itself, stripped of markup and clipped — never an
 *     `HTTP error!` blob, and never blank.
 *
 * `fallback` lets the caller name the act that failed ("could not be saved" vs
 * "could not be checked"); it is only reached when nothing else is readable.
 *
 * APPLY THIS EXACTLY ONCE, at the store. Step 3 CLIPS machine text at
 * `MAX_ERROR_CHARS`, which is right for a response body and wrong for a
 * sentence this module itself wrote — so a second pass over an
 * already-humanised message silently truncates correct copy. The store is the
 * single boundary (`WorkflowBuilder.store.ts` writes `error`); the panel and
 * the page render what it stored, verbatim.
 */
export function describeRequestError(
  error: unknown,
  steps: BuilderStep[],
  fallback: string = GENERIC_REQUEST_FAILURE,
): DescribedRequestError {
  const raw =
    typeof error === 'string'
      ? error
      : error instanceof Error
        ? error.message
        : ''

  const asFinding = humaniseValidatorFinding(raw, steps)
  if (asFinding) return { text: asFinding.text, finding: asFinding.identity }

  const fromMessage = HTTP_ERROR_RE.exec(raw)?.[1]
  const status = statusOf(error) ?? (fromMessage ? Number(fromMessage) : null)
  if (status != null) {
    const sentence = statusSentence(status)
    if (sentence) return { text: sentence, finding: null }
  }

  // An `HTTP error!` string whose status told us nothing is still a machine
  // artefact wrapped around a response body — do not paste it.
  if (HTTP_ERROR_RE.test(raw)) return { text: fallback, finding: null }
  return { text: tidyMachineText(raw) || fallback, finding: null }
}

/** `describeRequestError`'s sentence, for callers that need nothing else. */
export function humaniseRequestError(
  error: unknown,
  steps: BuilderStep[],
  fallback: string = GENERIC_REQUEST_FAILURE,
): string {
  return describeRequestError(error, steps, fallback).text
}
